import { TEAM } from "./engine.js";

const P = TEAM.PLAINTIFF;
const D = TEAM.DEFENDANT;

export const characters = [
  { position: "A1", name: "Mina", role: "Attorney", portrait: 0 },
  { position: "B1", name: "Bennett", role: "Paralegal", portrait: 1 },
  { position: "C1", name: "Yuki", role: "Investigator", portrait: 2 },
  { position: "D1", name: "Elias", role: "Accountant", portrait: 3 },
  { position: "A2", name: "Odette", role: "Engineer", portrait: 4 },
  { position: "B2", name: "Calvin", role: "Appraiser", portrait: 5 },
  { position: "C2", name: "Samira", role: "Medical consultant", portrait: 6 },
  { position: "D2", name: "Arthur", role: "Technology specialist", portrait: 7 },
  { position: "A3", name: "Priya", role: "Interpreter", portrait: 8 },
  { position: "B3", name: "Theo", role: "Research assistant", portrait: 9 },
  { position: "C3", name: "Nora", role: "Document reviewer", portrait: 10 },
  { position: "D3", name: "Hiro", role: "Damages consultant", portrait: 11 },
  { position: "A4", name: "Marisol", role: "Photographer", portrait: 12 },
  { position: "B4", name: "Inez", role: "Property specialist", portrait: 13 },
  { position: "C4", name: "Dev", role: "Records consultant", portrait: 14 },
  { position: "D4", name: "Quinn", role: "Trial support specialist", portrait: 15 },
];

const direct = (id, position, team, text) => ({ id, type: "direct", position, team, text });
const same = (id, a, b, text) => ({ id, type: "same", a, b, text });
const opposite = (id, a, b, text) => ({ id, type: "opposite", a, b, text });
const count = (id, group, value, team, number, text, positions) => ({ id, type: "count", group, value, team, count: number, text, positions });
const belowOpposite = (id, position, text) => ({ id, type: "belowOpposite", position, text });

function puzzle(config) {
  return { ...config, characters, solution: config.solution.split("") };
}

export const puzzles = [
  puzzle({
    id: "renovation-notes", level: "Tutorial", number: 1, difficultyRank: 1, difficulty: "Guided links",
    title: "Renovation Notes",
    summary: "A tenant and landlord disagree about damage caused during an apartment renovation.",
    solution: "PDDPPDPDDPPDDDPP",
    openingClues: ["p1-01"],
    clues: [
      direct("p1-01", "A1", P, "Mina is on the Plaintiff Team."),
      opposite("p1-02", "A1", "B1", "Mina and Bennett are on opposite teams."),
      same("p1-03", "B1", "C1", "Bennett and Yuki are on the same team."),
      count("p1-04", "row", 1, P, 2, "Exactly two people in Row 1 are on the Plaintiff Team."),
      same("p1-05", "D1", "A2", "Elias and Odette are on the same team."),
      opposite("p1-06", "A2", "B2", "Odette and Calvin are on opposite teams."),
      opposite("p1-07", "B2", "C2", "Calvin and Samira are on opposite teams."),
      count("p1-08", "row", 2, P, 2, "Exactly two people in Row 2 are on the Plaintiff Team."),
      same("p1-09", "D2", "A3", "Arthur and Priya are on the same team."),
      opposite("p1-10", "A3", "B3", "Priya and Theo are on opposite teams."),
      same("p1-11", "B3", "C3", "Theo and Nora are on the same team."),
      count("p1-12", "row", 3, P, 2, "Exactly two people in Row 3 are on the Plaintiff Team."),
      same("p1-13", "D3", "A4", "Hiro and Marisol are on the same team."),
      same("p1-14", "A4", "B4", "Marisol and Inez are on the same team."),
      opposite("p1-15", "B4", "C4", "Inez and Dev are on opposite teams."),
      count("p1-16", "row", 4, P, 2, "Exactly two people in Row 4 are on the Plaintiff Team."),
    ],
    reveals: { A1:["p1-02"], B1:["p1-03"], C1:["p1-04"], D1:["p1-05"], A2:["p1-06"], B2:["p1-07"], C2:["p1-08"], D2:["p1-09"], A3:["p1-10"], B3:["p1-11"], C3:["p1-12"], D3:["p1-13"], A4:["p1-14"], B4:["p1-15"], C4:["p1-16"] },
    intendedPath: ["A1","B1","C1","D1","A2","B2","C2","D2","A3","B3","C3","D3","A4","B4","C4","D4"],
  }),
  puzzle({
    id: "festival-order", level: "Tutorial", number: 2, difficultyRank: 2, difficulty: "Paired deductions",
    title: "Festival Order",
    summary: "A bakery and festival organizer dispute a canceled catering contract.",
    solution: "PPPDPPDDDDPDPDPD",
    openingClues: ["p2-01", "p2-02", "p2-03"],
    clues: [
      direct("p2-01", "A1", P, "Mina is on the Plaintiff Team."),
      same("p2-02", "B1", "C1", "Bennett and Yuki are on the same team."),
      count("p2-03", "row", 1, P, 3, "Exactly three people in Row 1 are on the Plaintiff Team."),
      opposite("p2-04", "D1", "A2", "Elias and Odette are on opposite teams."),
      opposite("p2-05", "B2", "C2", "Exactly one of Calvin and Samira is on the Plaintiff Team."),
      count("p2-06", "row", 2, P, 2, "Exactly two people in Row 2 are on the Plaintiff Team."),
      opposite("p2-07", "B2", "D2", "Calvin and Arthur are on opposite teams."),
      same("p2-08", "A3", "B3", "Priya and Theo are on the same team."),
      opposite("p2-09", "C3", "D3", "Exactly one of Nora and Hiro is on the Plaintiff Team."),
      count("p2-10", "row", 3, P, 1, "Exactly one person in Row 3 is on the Plaintiff Team."),
      same("p2-11", "C3", "A2", "Nora is on the same team as Odette."),
      same("p2-12", "B4", "D3", "Inez is on the same team as Hiro."),
      opposite("p2-13", "B4", "C4", "Inez and Dev are on opposite teams."),
      count("p2-14", "row", 4, P, 2, "Exactly two people in Row 4 are on the Plaintiff Team."),
      same("p2-15", "A4", "C4", "Marisol and Dev are on the same team."),
      opposite("p2-16", "C4", "D4", "Dev and Quinn are on opposite teams."),
    ],
    reveals: { D1:["p2-04"], A2:["p2-05","p2-06"], D2:["p2-07"], C2:["p2-08","p2-09","p2-10"], B3:["p2-11"], D3:["p2-12","p2-13","p2-14"], B4:["p2-15"], C4:["p2-16"] },
    intendedPath: ["A1","B1","C1","D1","A2","D2","B2","C2","A3","B3","C3","D3","B4","C4","A4","D4"],
  }),
  puzzle({
    id: "boundary-map", level: "Standard", number: 3, difficultyRank: 3, difficulty: "Parity and columns",
    title: "Boundary Map",
    summary: "Two neighbors disagree about the location of a shared property boundary.",
    solution: "PPPDDPDPDPPDPDPP",
    openingClues: ["p3-01", "p3-02", "p3-03"],
    clues: [
      count("p3-01", "row", 1, P, 3, "Exactly three people in Row 1 are on the Plaintiff Team."),
      same("p3-02", "B1", "C1", "Bennett and Yuki are on the same team."),
      opposite("p3-03", "A1", "D1", "Exactly one of Mina and Elias is on the Plaintiff Team."),
      same("p3-04", "A1", "B1", "Mina is on the same team as Bennett."),
      count("p3-05", "column", "A", P, 2, "Exactly two people in Column A are on the Plaintiff Team."),
      same("p3-06", "A2", "A3", "Odette and Priya are on the same team."),
      same("p3-07", "D4", "A4", "Quinn and Marisol are on the same team."),
      count("p3-08", "row", 4, P, 3, "Exactly three people in Row 4 are on the Plaintiff Team."),
      opposite("p3-09", "B4", "C4", "Exactly one of Inez and Dev is on the Plaintiff Team."),
      same("p3-10", "B4", "A2", "Inez is on the same team as Odette."),
      count("p3-11", "row", 3, P, 2, "Exactly two people in Row 3 are on the Plaintiff Team."),
      same("p3-12", "B3", "C3", "Theo and Nora are on the same team."),
      opposite("p3-13", "B2", "C2", "Exactly one of Calvin and Samira is on the Plaintiff Team."),
      same("p3-14", "D2", "B2", "Arthur is on the same team as Calvin."),
      count("p3-15", "row", 2, P, 2, "Exactly two people in Row 2 are on the Plaintiff Team."),
      same("p3-16", "D3", "A2", "Hiro is on the same team as Odette."),
    ],
    reveals: { B1:["p3-04"], A1:["p3-05","p3-06"], A4:["p3-07","p3-08","p3-09","p3-10"], A3:["p3-11","p3-12","p3-16"], D3:["p3-13","p3-14","p3-15"] },
    intendedPath: ["B1","C1","A1","D1","A2","A3","A4","D4","B4","C4","B3","C3","D3","B2","C2","D2"],
  }),
  puzzle({
    id: "bench-sketch", level: "Standard", number: 4, difficultyRank: 4, difficulty: "Corners and intersections",
    title: "Bench Sketch",
    summary: "An artist and library dispute the design of a commissioned reading bench.",
    solution: "DPPDPDPPDDDPPDDD",
    openingClues: ["p4-01", "p4-02", "p4-03"],
    clues: [
      count("p4-01", "corners", null, P, 1, "Exactly one corner belongs to the Plaintiff Team."),
      same("p4-02", "A1", "D1", "Both upper corners are on the same team."),
      opposite("p4-03", "A4", "D4", "The two lower corners are on opposite teams."),
      count("p4-04", "row", 1, P, 2, "Exactly two people in Row 1 are on the Plaintiff Team."),
      same("p4-05", "B1", "C1", "Bennett and Yuki are on the same team."),
      opposite("p4-06", "A1", "A2", "Mina and Odette are on opposite teams."),
      opposite("p4-07", "B2", "D2", "Calvin and Arthur are on opposite teams."),
      same("p4-08", "A2", "C2", "Odette and Samira are on the same team."),
      count("p4-09", "row", 2, P, 3, "Exactly three people in Row 2 are on the Plaintiff Team."),
      same("p4-18", "D2", "C2", "Arthur is on the same team as Samira."),
      same("p4-10", "A3", "A1", "Priya is on the same team as Mina."),
      count("p4-11", "column", "A", P, 2, "Exactly two people in Column A are on the Plaintiff Team."),
      same("p4-12", "D3", "D2", "Hiro and Arthur are on the same team."),
      count("p4-13", "row", 3, P, 1, "Exactly one person in Row 3 is on the Plaintiff Team."),
      same("p4-14", "B3", "A1", "Theo is on the same team as Mina."),
      count("p4-15", "row", 4, P, 1, "Exactly one person in Row 4 is on the Plaintiff Team."),
      same("p4-16", "B4", "D4", "Inez and Quinn are on the same team."),
      same("p4-17", "C4", "A1", "Dev is on the same team as Mina."),
    ],
    reveals: { A1:["p4-04","p4-05","p4-06"], A2:["p4-07","p4-08","p4-09","p4-18"], B2:["p4-10","p4-11"], A4:["p4-12","p4-13","p4-14"], D3:["p4-15","p4-16","p4-17"] },
    intendedPath: ["A1","D1","B1","C1","A2","C2","D2","B2","A3","A4","D4","D3","B3","C3","B4","C4"],
  }),
  puzzle({
    id: "antique-repair", level: "Standard", number: 5, difficultyRank: 5, difficulty: "Neighbor elimination",
    title: "Antique Repair",
    summary: "A customer claims a repair shop damaged an unusual mechanical antique.",
    solution: "DPPDPPPPPPDDPDPP",
    openingClues: ["p5-01", "p5-02", "p5-03", "p5-04"],
    clues: [
      direct("p5-01", "A1", D, "Mina is on the Defendant Team."),
      count("p5-02", "row", 1, P, 2, "Exactly two people in Row 1 are on the Plaintiff Team."),
      same("p5-03", "B1", "C1", "Bennett and Yuki are on the same team."),
      direct("p5-04", "C2", P, "Samira is on the Plaintiff Team."),
      belowOpposite("p5-05", "A1", "The person directly below Mina is on the opposite team."),
      opposite("p5-06", "D1", "B2", "Elias and Calvin are on opposite teams."),
      count("p5-07", "column", "A", P, 3, "Column A contains three Plaintiff Team members."),
      same("p5-08", "D2", "B3", "Arthur and Theo are on the same team."),
      same("p5-09", "C3", "D3", "Nora and Hiro are on the same team."),
      opposite("p5-10", "D2", "C3", "Arthur and Nora are on opposite teams."),
      count("p5-11", "neighbors", "C2", P, 5, "Samira has exactly five Plaintiff Team neighbors."),
      count("p5-12", "row", 3, P, 2, "Exactly two people in Row 3 are on the Plaintiff Team."),
      count("p5-13", "column", "B", P, 3, "Column B contains three Plaintiff Team members."),
      count("p5-14", "column", "C", P, 3, "Column C contains three Plaintiff Team members."),
      count("p5-15", "column", "D", P, 2, "Exactly two people in Column D are on the Plaintiff Team."),
    ],
    reveals: { A1:["p5-05"], D1:["p5-06"], A2:["p5-07"], B2:["p5-08","p5-09","p5-10","p5-11","p5-12"], D3:["p5-13","p5-14","p5-15"] },
    intendedPath: ["A1","B1","C1","D1","C2","A2","B2","A3","A4","D2","B3","C3","D3","B4","C4","D4"],
  }),
  puzzle({
    id: "greenhouse-door", level: "Standard", number: 6, difficultyRank: 6, difficulty: "Cross-board counts",
    title: "Greenhouse Door",
    summary: "A community garden and contractor dispute a missing greenhouse door.",
    solution: "DPDDPDPPDDDPPPDD",
    openingClues: ["p6-01", "p6-02", "p6-03"],
    clues: [
      count("p6-01", "corners", null, P, 1, "Exactly one corner belongs to the Plaintiff Team."),
      same("p6-02", "A1", "D1", "Both upper corners are on the same team."),
      opposite("p6-03", "A4", "D4", "The two lower corners are on opposite teams."),
      count("p6-04", "row", 1, P, 1, "Exactly one person in Row 1 is on the Plaintiff Team."),
      opposite("p6-05", "B1", "C1", "Exactly one of Bennett and Yuki is on the Plaintiff Team."),
      same("p6-06", "D2", "B1", "Arthur is on the same team as Bennett."),
      same("p6-07", "A2", "C2", "Odette and Samira are on the same team."),
      opposite("p6-08", "B2", "D2", "Calvin and Arthur are on opposite teams."),
      count("p6-09", "row", 2, P, 3, "Exactly three people in Row 2 are on the Plaintiff Team."),
      belowOpposite("p6-10", "A2", "The person directly below Odette is on the opposite team."),
      same("p6-11", "C3", "A3", "Nora and Priya are on the same team."),
      same("p6-12", "D3", "D2", "Hiro and Arthur are on the same team."),
      count("p6-13", "row", 3, P, 1, "Exactly one person in Row 3 is on the Plaintiff Team."),
      count("p6-14", "column", "B", P, 2, "Exactly two people in Column B are on the Plaintiff Team."),
      same("p6-15", "A4", "B4", "Marisol and Inez are on the same team."),
      same("p6-16", "C4", "A3", "Dev is on the same team as Priya."),
      opposite("p6-17", "A1", "B1", "Hana and Bennett are on opposite teams."),
    ],
    reveals: { A1:["p6-04","p6-05","p6-17"], B1:["p6-06","p6-07","p6-08","p6-09"], A2:["p6-10","p6-11","p6-12","p6-13"], B3:["p6-14"], B4:["p6-15","p6-16"] },
    intendedPath: ["A1","D1","B1","C1","D2","A2","B2","C2","A3","C3","D3","B3","B4","A4","D4","C4"],
  }),
  puzzle({
    id: "mural-license", level: "Challenge", number: 7, difficultyRank: 7, difficulty: "Linked systems",
    title: "Mural License",
    summary: "A muralist and market association dispute permission to reproduce a neighborhood artwork.",
    solution: "PPPDPDPDDPPDPDDP",
    openingClues: ["p7-01", "p7-02", "p7-03"],
    clues: [
      count("p7-01", "row", 1, P, 3, "Exactly three people in Row 1 are on the Plaintiff Team."),
      same("p7-02", "A1", "B1", "Mina and Bennett are on the same team."),
      opposite("p7-03", "C1", "D1", "Exactly one of Yuki and Elias is on the Plaintiff Team."),
      same("p7-04", "C1", "A1", "Yuki is on the same team as Mina."),
      count("p7-05", "column", "A", P, 3, "Column A contains three Plaintiff Team members."),
      opposite("p7-06", "A2", "A3", "Odette and Priya are on opposite teams."),
      same("p7-07", "A4", "A2", "Marisol is on the same team as Odette."),
      opposite("p7-08", "B2", "C2", "Exactly one of Calvin and Samira is on the Plaintiff Team."),
      same("p7-09", "D2", "B2", "Arthur is on the same team as Calvin."),
      count("p7-10", "row", 2, P, 2, "Exactly two people in Row 2 are on the Plaintiff Team."),
      same("p7-11", "B3", "C3", "Theo and Nora are on the same team."),
      count("p7-12", "row", 3, P, 2, "Exactly two people in Row 3 are on the Plaintiff Team."),
      same("p7-13", "B4", "C4", "Inez and Dev are on the same team."),
      count("p7-14", "row", 4, P, 2, "Exactly two people in Row 4 are on the Plaintiff Team."),
      same("p7-15", "D3", "A3", "Hiro is on the same team as Priya."),
      same("p7-16", "D4", "A2", "Quinn is on the same team as Odette."),
    ],
    reveals: { A1:["p7-04"], D1:["p7-05","p7-06","p7-07"], A2:["p7-08","p7-09","p7-10"], A3:["p7-11","p7-12","p7-15"], A4:["p7-13","p7-14","p7-16"] },
    intendedPath: ["A1","B1","C1","D1","A2","A3","A4","B2","C2","D2","B3","C3","D3","B4","C4","D4"],
  }),
  puzzle({
    id: "courtyard-lights", level: "Challenge", number: 8, difficultyRank: 8, difficulty: "Multi-clue finale",
    title: "Courtyard Lights",
    summary: "A café and lighting studio dispute an unfinished courtyard installation.",
    solution: "PPDPPDDPDPDPDDPD",
    openingClues: ["p8-01", "p8-02", "p8-03", "p8-04", "p8-05"],
    clues: [
      count("p8-01", "corners", null, P, 2, "Exactly two corners belong to the Plaintiff Team."),
      same("p8-02", "A1", "D1", "Both upper corners are on the same team."),
      same("p8-03", "A4", "D4", "Both lower corners are on the same team."),
      opposite("p8-04", "B1", "C1", "Exactly one of Bennett and Yuki is on the Plaintiff Team."),
      count("p8-05", "row", 1, P, 3, "Exactly three people in Row 1 are on the Plaintiff Team."),
      opposite("p8-06", "B1", "A4", "Bennett and Marisol are on opposite teams."),
      count("p8-07", "column", "D", P, 3, "Column D contains three Plaintiff Team members."),
      same("p8-08", "B2", "C2", "Calvin and Samira are on the same team."),
      count("p8-09", "row", 2, P, 2, "Exactly two people in Row 2 are on the Plaintiff Team."),
      count("p8-10", "column", "A", P, 2, "Exactly two people in Column A are on the Plaintiff Team."),
      opposite("p8-11", "B3", "C3", "Exactly one of Theo and Nora is on the Plaintiff Team."),
      count("p8-12", "row", 3, P, 2, "Exactly two people in Row 3 are on the Plaintiff Team."),
      opposite("p8-13", "B4", "C4", "Exactly one of Inez and Dev is on the Plaintiff Team."),
      count("p8-14", "row", 4, P, 1, "Exactly one person in Row 4 is on the Plaintiff Team."),
      same("p8-15", "B3", "C4", "Theo is on the same team as Dev."),
      count("p8-16", "neighbors", "D2", P, 2, "Arthur has exactly two Plaintiff Team neighbors."),
    ],
    reveals: { A1:["p8-06"], D1:["p8-07"], D4:["p8-08","p8-09","p8-10"], A3:["p8-11","p8-12"], D3:["p8-13","p8-14"], C2:["p8-15","p8-16"] },
    intendedPath: ["A1","D1","A4","D4","B1","C1","D2","D3","A2","B2","C2","A3","C3","B3","C4","B4"],
  }),
];

export function getPuzzle(id) {
  return puzzles.find((item) => item.id === id) || puzzles[0];
}
