import { TEAM } from "./engine.js";

const P = TEAM.PLAINTIFF;
const D = TEAM.DEFENDANT;

export const characters = [
  { position: "A1", name: "Mina", role: "Attorney", portrait: 0 },
  { position: "B1", name: "Bennett", role: "Paralegal", portrait: 1 },
  { position: "C1", name: "Yuki", role: "Investigator", portrait: 2 },
  { position: "D1", name: "Elias", role: "Accountant", portrait: 3 },
  { position: "A2", name: "Odette", role: "Engineer", portrait: 4 },
  { position: "B2", name: "Calvin", role: "Appraiser", portrait: 5 },
  { position: "C2", name: "Samira", role: "Medical consultant", portrait: 6 },
  { position: "D2", name: "Arthur", role: "Technology specialist", portrait: 7 },
  { position: "A3", name: "Priya", role: "Interpreter", portrait: 8 },
  { position: "B3", name: "Theo", role: "Research assistant", portrait: 9 },
  { position: "C3", name: "Nora", role: "Document reviewer", portrait: 10 },
  { position: "D3", name: "Hiro", role: "Damages consultant", portrait: 11 },
  { position: "A4", name: "Marisol", role: "Photographer", portrait: 12 },
  { position: "B4", name: "Inez", role: "Property specialist", portrait: 13 },
  { position: "C4", name: "Dev", role: "Records consultant", portrait: 14 },
  { position: "D4", name: "Quinn", role: "Trial support specialist", portrait: 15 },
];

const direct = (id, position, team, text) => ({ id, type: "direct", position, team, text });
const same = (id, a, b, text) => ({ id, type: "same", a, b, text });
const opposite = (id, a, b, text) => ({ id, type: "opposite", a, b, text });
const count = (id, group, value, team, number, text, positions) => ({ id, type: "count", group, value, team, count: number, text, positions });
const belowOpposite = (id, position, text) => ({ id, type: "belowOpposite", position, text });

function puzzle(config) {
  return { ...config, characters, solution: config.solution.split("") };
}

export const puzzles = [
  puzzle({
    id: "renovation-notes", level: "Tutorial", number: 1,
    title: "Renovation Notes",
    summary: "A tenant and landlord disagree about damage caused during an apartment renovation.",
    solution: "PDDPPPDPDDPPPPDD",
    openingClues: ["t1-01"],
    clues: [
      direct("t1-01", "A1", P, "Mina is on the Plaintiff Team."),
      opposite("t1-02", "A1", "B1", "Mina and Bennett are on opposite teams."),
      same("t1-03", "B1", "C1", "Bennett and Yuki are on the same team."),
      opposite("t1-04", "C1", "D1", "Yuki and Elias are on opposite teams."),
      same("t1-05", "D1", "A2", "Elias and Odette are on the same team."),
      same("t1-06", "A2", "B2", "Odette and Calvin are on the same team."),
      opposite("t1-07", "B2", "C2", "Calvin and Samira are on opposite teams."),
      opposite("t1-08", "C2", "D2", "Samira and Arthur are on opposite teams."),
      opposite("t1-09", "D2", "A3", "Arthur and Priya are on opposite teams."),
      same("t1-10", "A3", "B3", "Priya and Theo are on the same team."),
      opposite("t1-11", "B3", "C3", "Theo and Nora are on opposite teams."),
      same("t1-12", "C3", "D3", "Nora and Hiro are on the same team."),
      same("t1-13", "D3", "A4", "Hiro and Marisol are on the same team."),
      same("t1-14", "A4", "B4", "Marisol and Inez are on the same team."),
      opposite("t1-15", "B4", "C4", "Inez and Dev are on opposite teams."),
      same("t1-16", "C4", "D4", "Dev and Quinn are on the same team."),
    ],
    reveals: { A1:["t1-02"], B1:["t1-03"], C1:["t1-04"], D1:["t1-05"], A2:["t1-06"], B2:["t1-07"], C2:["t1-08"], D2:["t1-09"], A3:["t1-10"], B3:["t1-11"], C3:["t1-12"], D3:["t1-13"], A4:["t1-14"], B4:["t1-15"], C4:["t1-16"] },
    intendedPath: ["A1","B1","C1","D1","A2","B2","C2","D2","A3","B3","C3","D3","A4","B4","C4","D4"],
  }),
  puzzle({
    id: "festival-order", level: "Tutorial", number: 2,
    title: "Festival Order",
    summary: "A bakery and festival organizer dispute a canceled catering contract.",
    solution: "DPPDDDPPDDPPDPDP",
    openingClues: ["t2-01", "t2-02"],
    clues: [
      direct("t2-01", "D1", D, "Elias is on the Defendant Team."),
      same("t2-02", "A1", "D1", "Mina is on the same team as Elias."),
      opposite("t2-03", "A1", "B1", "Mina and Bennett are on opposite teams."),
      same("t2-04", "B1", "C1", "Bennett and Yuki are on the same team."),
      opposite("t2-05", "C1", "A2", "Yuki and Odette are on opposite teams."),
      same("t2-06", "A2", "B2", "Odette and Calvin are on the same team."),
      opposite("t2-07", "B2", "C2", "Exactly one of Calvin and Samira is on the Plaintiff Team."),
      same("t2-08", "C2", "D2", "Samira and Arthur are on the same team."),
      opposite("t2-09", "D2", "A3", "Arthur and Priya are on opposite teams."),
      same("t2-10", "A3", "B3", "Priya and Theo are on the same team."),
      opposite("t2-11", "B3", "C3", "Theo and Nora are on opposite teams."),
      same("t2-12", "C3", "D3", "Nora and Hiro are on the same team."),
      opposite("t2-13", "D3", "A4", "Hiro and Marisol are on opposite teams."),
      opposite("t2-14", "A4", "B4", "Marisol and Inez are on opposite teams."),
      opposite("t2-15", "B4", "C4", "Inez and Dev are on opposite teams."),
      opposite("t2-16", "C4", "D4", "Dev and Quinn are on opposite teams."),
    ],
    reveals: { A1:["t2-03"], B1:["t2-04"], C1:["t2-05"], A2:["t2-06"], B2:["t2-07"], C2:["t2-08"], D2:["t2-09"], A3:["t2-10"], B3:["t2-11"], C3:["t2-12"], D3:["t2-13"], A4:["t2-14"], B4:["t2-15"], C4:["t2-16"] },
    intendedPath: ["D1","A1","B1","C1","A2","B2","C2","D2","A3","B3","C3","D3","A4","B4","C4","D4"],
  }),
  puzzle({
    id: "boundary-map", level: "Standard", number: 3,
    title: "Boundary Map",
    summary: "Two neighbors disagree about the location of a shared property boundary.",
    solution: "PDPDDDPPP PDDD PDP".replaceAll(" ", ""),
    openingClues: ["s1-01", "s1-04", "s1-08", "s1-12", "s1-16"],
    clues: [
      direct("s1-01", "A1", P, "Mina is on the Plaintiff Team."),
      opposite("s1-02", "A1", "B1", "Mina and Bennett are on opposite teams."),
      opposite("s1-03", "B1", "C1", "Bennett and Yuki are on opposite teams."),
      count("s1-04", "row", 1, P, 2, "Exactly two people in Row 1 are on the Plaintiff Team."),
      same("s1-05", "D1", "A2", "Elias and Odette are on the same team."),
      same("s1-06", "A2", "B2", "Odette and Calvin are on the same team."),
      opposite("s1-07", "B2", "C2", "Calvin and Samira are on opposite teams."),
      count("s1-08", "row", 2, P, 2, "Exactly two people in Row 2 are on the Plaintiff Team."),
      same("s1-09", "D2", "A3", "Arthur and Priya are on the same team."),
      same("s1-10", "A3", "B3", "Priya and Theo are on the same team."),
      opposite("s1-11", "B3", "C3", "Theo and Nora are on opposite teams."),
      count("s1-12", "row", 3, P, 2, "Exactly two people in Row 3 are on the Plaintiff Team."),
      same("s1-13", "D3", "A4", "Hiro and Marisol are on the same team."),
      opposite("s1-14", "A4", "B4", "Marisol and Inez are on opposite teams."),
      opposite("s1-15", "B4", "C4", "Inez and Dev are on opposite teams."),
      count("s1-16", "row", 4, P, 2, "Exactly two people in Row 4 are on the Plaintiff Team."),
    ],
    reveals: { A1:["s1-02"], B1:["s1-03"], D1:["s1-05"], A2:["s1-06"], B2:["s1-07"], D2:["s1-09"], A3:["s1-10"], B3:["s1-11"], D3:["s1-13"], A4:["s1-14"], B4:["s1-15"] },
    intendedPath: ["A1","B1","C1","D1","A2","B2","C2","D2","A3","B3","C3","D3","A4","B4","C4","D4"],
  }),
  puzzle({
    id: "bench-sketch", level: "Standard", number: 4,
    title: "Bench Sketch",
    summary: "An artist and library dispute the design of a commissioned reading bench.",
    solution: "PDPPDDDDPDPPDPPD",
    openingClues: ["s2-01", "s2-05", "s2-09", "s2-13"],
    clues: [
      direct("s2-01", "A1", P, "Mina is on the Plaintiff Team."),
      opposite("s2-02", "A1", "A2", "Mina and Odette are on opposite teams."),
      opposite("s2-03", "A2", "A3", "Odette and Priya are on opposite teams."),
      opposite("s2-04", "A3", "A4", "Priya and Marisol are on opposite teams."),
      count("s2-05", "column", "B", D, 3, "Column B contains three Defendant Team members."),
      opposite("s2-06", "A1", "B1", "Mina and Bennett are on opposite teams."),
      same("s2-07", "B1", "B2", "Bennett and Calvin are on the same team."),
      same("s2-08", "B2", "B3", "Calvin and Theo are on the same team."),
      count("s2-09", "column", "C", P, 3, "Column C contains three Plaintiff Team members."),
      same("s2-10", "A1", "C1", "Yuki is on the same team as Mina."),
      opposite("s2-11", "C1", "C2", "Yuki and Samira are on opposite teams."),
      opposite("s2-12", "C2", "C3", "Samira and Nora are on opposite teams."),
      count("s2-13", "column", "D", P, 2, "Exactly two people in Column D are on the Plaintiff Team."),
      same("s2-14", "A1", "D1", "Elias is on the same team as Mina."),
      opposite("s2-15", "D1", "D2", "Elias and Arthur are on opposite teams."),
      opposite("s2-16", "D2", "D3", "Arthur and Hiro are on opposite teams."),
    ],
    reveals: { A1:["s2-02","s2-06","s2-10","s2-14"], A2:["s2-03"], A3:["s2-04"], B1:["s2-07"], B2:["s2-08"], C1:["s2-11"], C2:["s2-12"], D1:["s2-15"], D2:["s2-16"] },
    intendedPath: ["A1","A2","A3","A4","B1","B2","B3","B4","C1","C2","C3","C4","D1","D2","D3","D4"],
  }),
  puzzle({
    id: "antique-repair", level: "Standard", number: 5,
    title: "Antique Repair",
    summary: "A customer claims a repair shop damaged an unusual mechanical antique.",
    solution: "PDDPDDDPPPDDDPDP",
    openingClues: ["s3-01"],
    clues: [
      direct("s3-01", "A1", P, "Mina is on the Plaintiff Team."),
      opposite("s3-02", "A1", "B1", "Mina and Bennett are on opposite teams."),
      same("s3-03", "B1", "C1", "Bennett and Yuki are on the same team."),
      opposite("s3-04", "C1", "D1", "Yuki and Elias are on opposite teams."),
      opposite("s3-05", "D1", "A2", "Elias and Odette are on opposite teams."),
      same("s3-06", "A2", "B2", "Odette and Calvin are on the same team."),
      same("s3-07", "B2", "C2", "Calvin and Samira are on the same team."),
      opposite("s3-08", "C2", "D2", "Samira and Arthur are on opposite teams."),
      same("s3-09", "D2", "A3", "Arthur and Priya are on the same team."),
      same("s3-10", "A3", "B3", "Priya and Theo are on the same team."),
      count("s3-11", "neighbors", "C2", P, 3, "Samira has exactly three Plaintiff Team neighbors."),
      same("s3-12", "C3", "D3", "Nora and Hiro are on the same team."),
      same("s3-13", "D3", "A4", "Hiro and Marisol are on the same team."),
      opposite("s3-14", "A4", "B4", "Marisol and Inez are on opposite teams."),
      opposite("s3-15", "B4", "C4", "Inez and Dev are on opposite teams."),
      opposite("s3-16", "C4", "D4", "Dev and Quinn are on opposite teams."),
    ],
    reveals: { A1:["s3-02"], B1:["s3-03"], C1:["s3-04"], D1:["s3-05"], A2:["s3-06"], B2:["s3-07"], C2:["s3-08"], D2:["s3-09"], A3:["s3-10"], B3:["s3-11"], C3:["s3-12"], D3:["s3-13"], A4:["s3-14"], B4:["s3-15"], C4:["s3-16"] },
    intendedPath: ["A1","B1","C1","D1","A2","B2","C2","D2","A3","B3","C3","D3","A4","B4","C4","D4"],
  }),
  puzzle({
    id: "greenhouse-door", level: "Standard", number: 6,
    title: "Greenhouse Door",
    summary: "A community garden and contractor dispute a missing greenhouse door.",
    solution: "DPDDDPDDDPPPDPPP",
    openingClues: ["s4-01", "s4-04"],
    clues: [
      direct("s4-01", "A1", D, "Mina is on the Defendant Team."),
      opposite("s4-02", "A1", "B1", "Mina and Bennett are on opposite teams."),
      opposite("s4-03", "B1", "C1", "Bennett and Yuki are on opposite teams."),
      count("s4-04", "corners", null, P, 1, "Exactly one corner belongs to the Plaintiff Team."),
      same("s4-05", "C1", "A2", "Yuki and Odette are on the same team."),
      opposite("s4-06", "A2", "B2", "Odette and Calvin are on opposite teams."),
      opposite("s4-07", "B2", "C2", "Calvin and Samira are on opposite teams."),
      same("s4-08", "C2", "D2", "Samira and Arthur are on the same team."),
      same("s4-09", "D2", "A3", "Arthur and Priya are on the same team."),
      opposite("s4-10", "A3", "B3", "Priya and Theo are on opposite teams."),
      same("s4-11", "B3", "C3", "Theo and Nora are on the same team."),
      same("s4-12", "C3", "D3", "Nora and Hiro are on the same team."),
      opposite("s4-13", "D3", "A4", "Hiro and Marisol are on opposite teams."),
      opposite("s4-14", "A4", "B4", "Marisol and Inez are on opposite teams."),
      same("s4-15", "B4", "C4", "Inez and Dev are on the same team."),
      same("s4-16", "C4", "D4", "Dev and Quinn are on the same team."),
    ],
    reveals: { A1:["s4-02"], B1:["s4-03"], C1:["s4-05"], A2:["s4-06"], B2:["s4-07"], C2:["s4-08"], D2:["s4-09"], A3:["s4-10"], B3:["s4-11"], C3:["s4-12"], D3:["s4-13"], A4:["s4-14"], B4:["s4-15"], C4:["s4-16"] },
    intendedPath: ["A1","B1","C1","A2","B2","C2","D2","A3","B3","C3","D3","A4","B4","C4","D4","D1"],
  }),
  puzzle({
    id: "mural-license", level: "Challenge", number: 7,
    title: "Mural License",
    summary: "A muralist and market association dispute permission to reproduce a neighborhood artwork.",
    solution: "PDPPDDDPDPDDPDPD",
    openingClues: ["c1-01"],
    clues: [
      direct("c1-01", "A1", P, "Mina is on the Plaintiff Team."),
      opposite("c1-02", "A1", "B1", "Mina and Bennett are on opposite teams."),
      count("c1-03", "row", 1, P, 3, "Exactly three people in Row 1 are on the Plaintiff Team."),
      same("c1-04", "C1", "D1", "Yuki and Elias are on the same team."),
      opposite("c1-05", "C1", "A2", "Yuki and Odette are on opposite teams."),
      opposite("c1-06", "D1", "B2", "Elias and Calvin are on opposite teams."),
      same("c1-07", "B2", "C2", "Calvin and Samira are on the same team."),
      opposite("c1-08", "C2", "D2", "Samira and Arthur are on opposite teams."),
      same("c1-09", "A2", "A3", "Odette and Priya are on the same team."),
      opposite("c1-10", "A3", "B3", "Priya and Theo are on opposite teams."),
      opposite("c1-11", "B3", "C3", "Theo and Nora are on opposite teams."),
      same("c1-12", "C3", "D3", "Nora and Hiro are on the same team."),
      opposite("c1-13", "D3", "A4", "Hiro and Marisol are on opposite teams."),
      opposite("c1-14", "A4", "B4", "Marisol and Inez are on opposite teams."),
      opposite("c1-15", "B4", "C4", "Inez and Dev are on opposite teams."),
      opposite("c1-16", "C4", "D4", "Dev and Quinn are on opposite teams."),
    ],
    reveals: { A1:["c1-02"], B1:["c1-03","c1-04"], C1:["c1-05"], D1:["c1-06"], B2:["c1-07"], C2:["c1-08"], A2:["c1-09"], A3:["c1-10"], B3:["c1-11"], C3:["c1-12"], D3:["c1-13"], A4:["c1-14"], B4:["c1-15"], C4:["c1-16"] },
    intendedPath: ["A1","B1","C1","D1","A2","B2","C2","D2","A3","B3","C3","D3","A4","B4","C4","D4"],
  }),
  puzzle({
    id: "courtyard-lights", level: "Challenge", number: 8,
    title: "Courtyard Lights",
    summary: "A café and lighting studio dispute an unfinished courtyard installation.",
    solution: "DPPDPPDPPDDPDPPD",
    openingClues: ["c2-01", "c2-02", "c2-03"],
    clues: [
      direct("c2-01", "A1", D, "Mina is on the Defendant Team."),
      count("c2-02", "column", "B", P, 3, "Column B contains three Plaintiff Team members."),
      same("c2-03", "B1", "B2", "Bennett and Calvin are on the same team."),
      same("c2-04", "B1", "C1", "Bennett and Yuki are on the same team."),
      opposite("c2-05", "C1", "D1", "Yuki and Elias are on opposite teams."),
      opposite("c2-06", "D1", "A2", "Elias and Odette are on opposite teams."),
      opposite("c2-07", "B2", "C2", "Calvin and Samira are on opposite teams."),
      opposite("c2-08", "C2", "D2", "Samira and Arthur are on opposite teams."),
      same("c2-09", "D2", "A3", "Arthur and Priya are on the same team."),
      opposite("c2-10", "A3", "B3", "Priya and Theo are on opposite teams."),
      same("c2-11", "B3", "C3", "Theo and Nora are on the same team."),
      opposite("c2-12", "C3", "D3", "Nora and Hiro are on opposite teams."),
      opposite("c2-13", "D3", "A4", "Hiro and Marisol are on opposite teams."),
      opposite("c2-14", "A4", "B4", "Marisol and Inez are on opposite teams."),
      same("c2-15", "B4", "C4", "Inez and Dev are on the same team."),
      opposite("c2-16", "C4", "D4", "Dev and Quinn are on opposite teams."),
    ],
    reveals: { B1:["c2-04"], C1:["c2-05"], D1:["c2-06"], B2:["c2-07"], C2:["c2-08"], D2:["c2-09"], A3:["c2-10"], B3:["c2-11"], C3:["c2-12"], D3:["c2-13"], A4:["c2-14"], B4:["c2-15"], C4:["c2-16"] },
    intendedPath: ["A1","B1","B2","C1","D1","A2","C2","D2","A3","B3","C3","D3","A4","B4","C4","D4"],
  }),
];

export function getPuzzle(id) {
  return puzzles.find((item) => item.id === id) || puzzles[0];
}
